src/model/__test__/Edge.spec.ts, src/model/__test__/Node.spec.ts, src/model/__test__/__snapshots__/Edge.spec.ts.snap, src/model/__test__/__snapshots__/Node.spec.ts.snap, src/model/cluster/__test__/Digraph.spec.ts, src/model/cluster/__test__/Graph.spec.ts, src/model/cluster/__test__/Subgraph.spec.ts, src/model/cluster/__test__/__snapshots__/Digraph.spec.ts.snap, src/model/cluster/__test__/__snapshots__/Graph.spec.ts.snap, src/model/cluster/__test__/__snapshots__/Subgraph.spec.ts.snap, src/model/values/__test__/valueType.spec.ts, src/model/values/valueType.ts
```ts
const node = new Node('test');
node.attributes.set('label', '<<B>this is test</B>>');
console.log(node.toDot());
```
```dot
"test" [
label = <<B>this is test</B>>,
];
```
=> Support HTML Like label syntax

src/__test__/__snapshots__/usecase.spec.ts.snap, src/__test__/usecase.spec.ts, src/model/Attributes.ts, src/model/Edge.ts, src/model/Node.ts, src/model/__test__/Attributes.spec.ts, src/model/__test__/Edge.spec.ts, src/model/__test__/Node.spec.ts, src/model/__test__/__snapshots__/Attributes.spec.ts.snap, src/model/__test__/__snapshots__/Edge.spec.ts.snap, src/model/__test__/__snapshots__/Node.spec.ts.snap, src/model/cluster/Cluster.ts, src/model/cluster/__test__/Digraph.spec.ts, src/model/cluster/__test__/Graph.spec.ts, src/model/cluster/__test__/Subgraph.spec.ts, src/model/cluster/__test__/__snapshots__/Digraph.spec.ts.snap, src/model/cluster/__test__/__snapshots__/Graph.spec.ts.snap, src/model/cluster/__test__/__snapshots__/Subgraph.spec.ts.snap, src/utils/dot-rendering.ts
```typescript
const G = digraph('G', g => {
g.comment = 'This is directed graph.';
const a = g.node('aa');
a.comment = 'This is node a.';
const b = g.node('bb');
b.comment = 'This is node b.';
const c = g.node('cc');
c.comment = 'This is node c.';
g.edge([a, b, c], e => {
e.comment = 'This is edge.\nIt connects a, b and c.';
e.attributes.set('color', 'red');
e.attributes.comment = 'Edge line will draw with red.';
});
g.subgraph('A', A => {
A.comment = 'It is subgraph A.\nIt is not cluster';
A.node('Aaa', n => {
n.comment = 'This is node Aaa in subgraph A.';
n.attributes.comment = 'It will be filled by pink.';
n.attributes.set('color', 'pink');
});
});
});
```
```dot
// This is directed graph.
digraph G {
// This is node a.
aa;
// This is node b.
bb;
// This is node c.
cc;
// It is …
```
=> Add comment prop for graphviz objects

src/__test__/__snapshots__/usecase.spec.ts.snap, src/__test__/usecase.spec.ts, src/model/Node.ts, src/model/cluster/Cluster.ts, src/utils/dot-rendering.ts
```typescript
import { Node } from 'ts-graphviz';
const node = new Node('example');
// API that already exists
node.port('port').toDot();
// Output:
// example:port
// APIs supported this time
node.port({ port: 'port', compass: 'w' }).toDot();
// Output:
// example:port:w
```
=> Support compass port

src/model/Attributes.ts, src/model/AttributesBase.ts, src/model/__test__/Attributes.spec.ts, src/model/__test__/__snapshots__/Attributes.spec.ts.snap, src/model/cluster/Cluster.ts, src/model/cluster/__test__/Digraph.spec.ts, src/model/cluster/__test__/Graph.spec.ts, src/model/cluster/__test__/Subgraph.spec.ts, src/model/cluster/__test__/__snapshots__/Digraph.spec.ts.snap, src/model/cluster/__test__/__snapshots__/Graph.spec.ts.snap, src/model/cluster/__test__/__snapshots__/Subgraph.spec.ts.snap
```typescript
const g = new Digraph();
g.apply({
layout: 'dot',
dpi: 360,
});
g.toDot();
// digraph {
//   layout = dot;
//   dpi = 360;
// }
```
Enable to set attributes at once with object
```typescript
const attrs = new Attributes();
attrs.apply({
label: 'this is test',
color: 'red',
fontsize: 16,
});
attrs.toDot();
// [
//  label = \\"this is test\\",
//  color = red,
//  fontsize = 16,
// ]
```
=> Add attributes APIs

README.md, src/__test__/__snapshots__/usecase.spec.ts.snap, src/__test__/usecase.spec.ts, src/model/ID.ts, src/model/__test__/__snapshots__/Attributes.spec.ts.snap, src/model/__test__/__snapshots__/Digraph.spec.ts.snap, src/model/__test__/__snapshots__/Edge.spec.ts.snap, src/model/__test__/__snapshots__/Graph.spec.ts.snap, src/model/__test__/__snapshots__/Node.spec.ts.snap, src/model/__test__/__snapshots__/Subgraph.spec.ts.snap
There are several cases where quote should be used for IDs but didn't implement, such as:
1. When label is "node", it should be quoted, otherwise dot can't parse it correctly (i.e. `label = node` results in syntax error);
2. When label contains `.`, it should be marked in quote.
I think it might be safe to simply quote all IDs, no matter it's necessary or not.
=> fix: use quote for IDs

src/model/AttributesBase.ts, src/model/__test__/Attributes.spec.ts, src/types.ts
There was no API that can delete/clear the contents of `Attributes`.
Improved API of `Attributes` class and added type information.
- add `delete/clear` methods to `BaseAttributes` .
- add `XxxAttributes` type.
=> Improve Attributes API

LICENSE, README.md, package.json
The repository path is incorrect due to the effect of migrating the repository to the ts-graphviz organization.
Corrected to the correct path.
=> Fix repository url

src/__test__/__snapshots__/usecase.spec.ts.snap, src/model/Context.ts, src/model/Node.ts
When undeclared Node was used as the target of Edge, there was a problem that Node was declared in the cluster.
An object for handling an undefined Node called ForwardRefNode is used internally, and it is modified so that Node is not declared in the cluster.
=> Add ForwardRefNode object

src/model/__tests__/clusters.spec.ts, src/model/clusters.ts, src/model/edges.ts, src/model/nodes.ts, src/render/__tests__/__snapshots__/edges.spec.ts.snap, src/render/__tests__/edges.spec.ts, src/render/renderer.ts, src/render/utils.ts, src/types.ts, tsconfig.json
Could not group Edge targets.
When creating Edges, specify the Nodes as an array so that they can be grouped.
```ts
const root = new Digraph();
const [node1, node2, node3, node4] = Array(4)
.fill(true)
.map((_, i) => root.createNode(`node${i + 1}`));
const edge = new Edge([node1, [node2, node3], node4]);
root.addEdge(edge);
console.log(toDot(root));
```
to be
```dot
digraph {
"node1" -> {"node2" "node3"} -> "node4";
}
```
=> Add grouped edge target

src/model/attributes-base.ts, src/render/__tests__/__snapshots__/attributes.test.ts.snap, src/render/__tests__/attributes.test.ts
There was a problem that rendering failed when undefined was included when the value was reflected in the attribute as an object.
```ts
const subgraph = new Subgraph();
subgraph.apply({
color: undefined,
});
toDot(subgraph); // throw Error
```
Fixed to check whether null or undefined is included when setting the value.
=> add attribute undefined value validation

src/model/__tests__/clusters.spec.ts, src/model/__tests__/edges.spec.ts, src/model/clusters.ts, src/model/edges.ts
When creating `createEdge` from Cluster, an error is output by checking the number and type of EdgeTarget, but no error is output when creating by `new Edge(...)`.
close #151
=> Fix edge targets validation

.github/workflows/node-ci.yml
To temporarily avoid the problem that Graphviz for Windows is experiencing with the 2.44 version. #278
=> stop running CI on Windows

src/model/__tests__/clusters.spec.ts, src/model/clusters.ts, src/types.ts
The API for specifying common attributes for objects in a cluster was not intuitive.
see #252
Added an API for specifying common attributes for objects in a cluster, so that common attributes can be set in the same way as in the dot language.
Updated documentation to avoid confusion on usage since we are using overload.
=> Added API to specify common attributes in a cluster.

package.json
When Node.js supports ESModule, it is now set in the `exports` field instead of the `module` field in package.json.
Since this module uses the `module` field, there was a problem that ESModule could not be used.
Fixed to use exports field.
https://nodejs.org/api/packages.html
=> add exports field for ESModule

src/ast/model-shim/from-model/plugins/EdgePlugin.ts, test/edge-group.test.ts
The conversion failed when specifying a NodeRefGroup for the following Edge target.
```ts
digraph((g) => {
g.edge(['a', ['b', 'c']]);
});
```
EdgePlugin of FromModelConverter was modified to allow conversion of NodeRefGroup.
It can be converted as follows.
```dot
digraph {
"a" -> {"b" "c"};
}
```
=> fix: fix EdgePlugin for NodeRefGroup to AST conversion

package.json, rollup.config.js, yarn.lock
Inclusion of ts-graphviz package in CommonJS format `require()` fails.
The error occurred because the built `.cjs` file references `.js`.
Replace `.js` with `.cjs` in the build artifacts.
=> Resupport broken CommonJS module

src/adapter/deno/mod.js
Uncaught TypeError: stdout is not piped" error on Deno's E2E test.
Some investigation was done and fixed.
JOB: https://github.com/ts-graphviz/ts-graphviz/actions/runs/3815332614/jobs/6490249871#step:10:464
- Specified stdout as piped in deno.Command.
- Fixed behavior in case of missing files.
=> fix: fix for deno e2e test failed

src/ast/dot-shim/parser/__snapshots__/parse.test.ts.snap, src/ast/dot-shim/parser/__tests__/ast/ER.dot, src/ast/dot-shim/parser/__tests__/ast/Linux_kernel_diagram.dot, src/ast/dot-shim/parser/__tests__/ast/bazel.dot, src/ast/dot-shim/parser/__tests__/ast/cluster.dot, src/ast/dot-shim/parser/__tests__/ast/crazy.dot, src/ast/dot-shim/parser/__tests__/ast/datastruct.dot, src/ast/dot-shim/parser/__tests__/ast/fsm.dot, src/ast/dot-shim/parser/__tests__/ast/gradient_angles.dot, src/ast/dot-shim/parser/__tests__/ast/gradient_cluster.dot, src/ast/dot-shim/parser/__tests__/ast/gradient_colors.dot, src/ast/dot-shim/parser/__tests__/ast/gradient_datastruct.dot, src/ast/dot-shim/parser/__tests__/ast/gradient_g_c_n.dot, src/ast/dot-shim/parser/__tests__/ast/gradient_linear_angle.dot, src/ast/dot-shim/parser/__tests__/ast/gradient_radial_angle.dot, src/ast/dot-shim/parser/__tests__/ast/gradient_table.dot, src/ast/dot-shim/parser/__tests__/ast/grid.dot, src/ast/dot-shim/parser/__tests__/ast/neural-network.dot, src/ast/dot-shim/parser/__tests__/ast/ninja.dot, src/ast/dot-shim/parser/__tests__/ast/philo.dot, src/ast/dot-shim/parser/__tests__/ast/profile.dot, src/ast/dot-shim/parser/__tests__/ast/psg.dot, src/ast/dot-shim/parser/__tests__/ast/sdh.dot, src/ast/dot-shim/parser/__tests__/ast/siblings.dot, src/ast/dot-shim/parser/__tests__/ast/softmaint.dot, src/ast/dot-shim/parser/__tests__/ast/switch.dot, src/ast/dot-shim/parser/__tests__/ast/traffic_lights.dot, src/ast/dot-shim/parser/__tests__/ast/transparency.dot, src/ast/dot-shim/parser/__tests__/ast/unix.dot, src/ast/dot-shim/parser/dot.peggy
Fixes #757 
Fix Parser.
Special thanks for @diegoquinteiro !
=> fix AttributeList kind AST case

package.json, rollup.config.js, src/adapter/deno/mod.d.ts, src/adapter/deno/mod.js, src/adapter/node/index.ts, src/adapter/node/to-file.ts, src/adapter/node/to-stream.ts, src/adapter/node/utils.ts, src/adapter/types/index.ts, src/adapter/utils/index.ts
fix #739 
```ts
export type Format = 'png' | 'svg' | 'json' | 'jpg' | 'pdf' | 'xdot' | 'plain' | 'dot_json';
export type Layout = 'dot' | 'neato' | 'fdp' | 'sfdp' | 'circo' | 'twopi' | 'nop' | 'nop2' | 'osage' | 'patchwork';
export interface NeatoOptions {
layout: 'neato';
/**
* Sets no-op flag in neato.
*/
noop?: number;
/**
* Reduce graph.
*/
reduce?: boolean;
}
export interface FdpOptions {
layout: 'fdp';
/**
* Use grid.
*
* @default true
*/
grid?: boolean;
/**
* Use old attractive force
*
* @default true
*/
oldAttractive?: boolean;
/**
* Set number of iterations.
*/
iterations?: number;
/**
* Set unscaled factor
*/
unscaledFactor?: number;
/**
* Set overlap expansion factor.
*/
overlapExpansionFactor?: number;
/**
* Set temperature.
*/
temperature?: number;
}
export interface …
```
=> Add more options for adapter module

src/adapter/node/to-stream.ts, src/adapter/types/index.ts
Exception handling was lax and error details could not be obtained from standard errors.
Standard errors and syscall errors can now be retrieved.
=> Add error handling for adapter module

src/adapter/utils/index.ts
Space in the value passed to the command's options
was not included in the value passed to the command's options, an unintended error would occur.
=> fix to escape option values on adapter module

package.json, src/ast/dot-shim/parser/__tests__/real-world.test.ts, src/ast/dot-shim/parser/dot.peggy, src/ast/dot-shim/parser/parse.ts, src/ast/dot-shim/parser/peggy.options.json, yarn.lock
See https://github.com/metadevpro/ts-pegjs/pull/86
Rename to `DotSyntaxError`.
=> fix: rename SyntaxError to let not override native SyntaxError

src/common/attribute/attribute.ts, src/common/type/types.ts
Specifying an empty string for resetting attribute values was not possible due to TypeScript type restrictions.
```dot
a -> b [style=""]
```
Introduced the Blank type, allowing the reset to be specified.
The default value of `""` can be set to blank.
=> add Blank type for reset attribute

package.json, tsconfig.json
Code documentation is included in both the type definition file and JavaScript source code in the library output.
This leads to an increase in bundle size and degrades distributability.
Modify the build process so that only the code documentation is included in the type definition and only the source code in the JavaScript.
=> chaos: remove code doc from JS code, not from d.ts

jest.config.json
The test was failing after the E2E test was conducted.
This was due to a problem with the jest package resolution g not working properly, as the E2E test emulated the installation of ts-graphviz under the e2e directory.
Added jest setting to ignore under e2e directory.
=> fix: Add jest setting for resolve test failed after e2e test

src/adapter/types/index.ts, src/common/attribute/attribute.ts, src/common/attribute/keys.ts, src/common/type/types.ts, src/utils/type.ts
String types could be freely added externally from outside the library, but could not be removed.
Type manipulation is now possible by users setting the type of `$exclude` as well as addition.
=> feat: Support exclude types

src/common/models.ts, src/core/models/AttributesBase.ts
The type check of the value corresponding to the key of the set method was not performed.
```ts
graph.attributes.edge.set(attribute.color, 's'); // it should be error, but it is not error
```
This PR fixes the problem by adding a type check to the set method.
```ts
export interface Attributes<T extends AttributeKey> {
...
get<K extends T>(key: K): Attribute<K> | undefined;
set<K extends T>(key: K, value: Attribute<K>): void;
...
}
```
close #900
=> fix: Add Type validation for get/set method

.github/workflows/generate-changeset-on-dependabot.yaml
This pull request adds a new workflow for generating dependency updates changeset. The workflow is triggered when a pull request is made by the dependabot[bot] user. It generates a changeset file with the necessary updates for the dependencies and commits it to the repository.
=> Add workflow for generating dependency updates changeset

.github/workflows/main.yaml
This pull request introduces a small change to the GitHub Actions workflow configuration. It adds support for manually triggering the workflow using the `workflow_dispatch` event.
* [`.github/workflows/main.yaml`](diffhunk://#diff-71cabc4177e41ea8f15a89eb65398fa8187739f68a2762706d84885cd8b2ddc3R7): Added the `workflow_dispatch` event under the `on:` section to allow manual triggering of the workflow.
=> chore: enable manual triggering of the main workflow
